// Better Auth core tables (user, session, account, verification).
//
// Hand-written to match the exact schema Better Auth 1.7.2 requires
// (verified against node_modules/@better-auth/core's `getAuthTables`
// output for this project's config) rather than generated by the
// `@better-auth/cli` package, whose latest published version (1.4.21,
// itself marked deprecated) targets an older core and does not agree
// with the installed better-auth/@better-auth/core 1.7.2 field set
// (e.g. it does not know about the `account.issuer` field below).
//
// `user` additionally carries the app's onboarding/scheduling fields via
// Better Auth's `user.additionalFields` config (see src/server/auth/auth.ts).
import { boolean, integer, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { availabilitySchedules } from "./availability";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),

  // --- additional app fields (declared via user.additionalFields) ---
  username: text("username").unique(),
  timezone: text("timezone").notNull().default("UTC"),
  welcomeText: text("welcome_text"),
  weekStart: integer("week_start").notNull().default(0),
  // References availabilitySchedules.id (uuid); declared with AnyPgColumn to
  // break the auth.ts <-> availability.ts <-> auth.ts import cycle (the
  // schedule itself references user.id).
  defaultScheduleId: uuid("default_schedule_id").references(
    (): AnyPgColumn => availabilitySchedules.id,
    { onDelete: "set null" },
  ),
  onboardingCompletedAt: timestamp("onboarding_completed_at", { withTimezone: true }),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    // Identifies the issuing authority for this credential/OAuth link
    // (e.g. "credential" for email+password, or the OAuth provider's
    // issuer URL). Required by Better Auth 1.7.2's account-linking model.
    issuer: text("issuer").notNull(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("account_issuer_account_id_unique").on(table.issuer, table.accountId)],
);

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;
export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;
export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;
